### ISSUE TITLE
選択肢の順番を変更したい

### ISSUE THREAD

**Issue by Yu-Takasaki** [Yu-Takasaki/aqours6thcolor#7]
## 改修内容
プルダウンの選択肢の順番を変更したい。

1. 1塁側or3塁側を選択した際の選択肢の並び方を以下のように変更
T2-T8
L2-L10
D2-D10
301-378
379<- 179も同様にここに移動したい
380-384

**Comment by pyo940216** [comment]
#9 で対応

表示順番については実装都合上下記のように対応
> 301-378
> 379<- 179も同様にここに移動したい
> 380-384
> D2-D10
> L2-L10
> T2-T8
